// ESLint flat config: correctness checks only (no stylistic/formatting rules).
import js from '@eslint/js';
import globals from 'globals';

export default [
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'src/wasm/**', // generated by wasm-bindgen
      'src/xcross-wasm/**', // generated by emscripten
      'test-results/**',
      'playwright-report/**',
      'wasm-core/target/**',
      'wasm-core/pkg/**',
    ],
  },
  js.configs.recommended,
  {
    files: ['**/*.{js,mjs}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
    },
    linterOptions: {
      reportUnusedDisableDirectives: 'warn',
    },
    rules: {
      'no-unused-vars': ['warn', {
        args: 'none',
        caughtErrors: 'none',
        varsIgnorePattern: '^_',
        destructuredArrayIgnorePattern: '^_',
        ignoreRestSiblings: true,
      }],
      // Catches TDZ ReferenceErrors: a let/const/class used before its
      // declaration in the same scope. `variables/classes: false` only skips
      // references from nested functions (closures called later), which are
      // safe; undeclared names in other scopes are caught by no-undef.
      'no-use-before-define': ['error', { functions: false, classes: false, variables: false }],
      eqeqeq: ['error', 'smart'],
      'no-shadow': 'off',
      // Best-effort `try { localStorage... } catch {}` is an intentional idiom.
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-self-compare': 'error',
      'no-template-curly-in-string': 'warn',
      'no-unreachable-loop': 'error',
      'no-constructor-return': 'error',
      'array-callback-return': ['error', { allowImplicit: true }],
    },
  },
  {
    // Browser app code.
    files: ['src/**/*.js'],
    languageOptions: {
      globals: {
        ...globals.browser,
        __CUBESIGHT_REVISION__: 'readonly', // injected by vite.config.js `define`
      },
    },
  },
  {
    // Isomorphic modules also used from Node (unit tests, scripts/); they
    // guard Node-only globals with `typeof` checks.
    files: ['src/recorder.js', 'src/recording-replay.js', 'src/recording-harness.js'],
    languageOptions: { globals: { ...globals.node } },
  },
  {
    files: ['src/**/*-worker.js', 'src/**/*.worker.js'],
    languageOptions: { globals: { ...globals.worker } },
  },
  {
    // Node-side tooling. Playwright specs also contain page.evaluate()
    // callbacks that run in the browser, so tests get both sets.
    files: ['tests/**/*.{js,mjs}', 'pwa-tests/**/*.{js,mjs}'],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
  },
  {
    files: ['scripts/**/*.{js,mjs}', '*.config.js', 'eslint.config.js'],
    languageOptions: { globals: { ...globals.node } },
  },
  {
    // Design mockup generators: Node scripts that also run code in a headless
    // browser page (page.evaluate).
    files: ['docs/**/*.{js,mjs}'],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
  },
];
