// Hand-written semantic labels for values that the extractor measures from the
// design SVGs. Only NAMES and prose live here; every number comes from the SVG.
// A value the SVG uses but this file does not name is reported as "unlabelled".

/** hex -> [token, role]. Sticker shades are keyed by their top-face hex below. */
export const COLOR_ROLES = {
  '#141311': ['bg', 'page background; also the dark ink on light pills (start / next scramble) and the marker-dot centre'],
  '#0d0c0b': ['sheet', 'phone-sheet backdrop outside the 390x844 devices (A-09, A-12 only)'],
  '#1d1b18': ['cube-body', 'cube hexagon silhouette / sticker gap colour'],
  '#2b2925': ['keycap', 'keycap fill and secondary-button fill'],
  '#2a2823': ['ring-template', 'inspection-only inner ring (r268) showing the stage layout to come'],
  '#34312b': ['ring-idle', 'ring segment not yet reached; outline of ghost pills, phone device border'],
  '#4d3715': ['warn-dim', 'dark amber fill: inspection overrun segment (+2), wrong-turn pill, review current-move pill'],
  '#6d675c': ['text-faint', 'faintest text (stage labels not reached, orbit move labels done, move counter), ticks, A-02 completed arcs'],
  '#9a9486': ['text-dim', 'secondary text: inactive nav, config line, stats lines, keycap action words, outlined buttons'],
  '#d9d2c3': ['keycap-label', 'text on a keycap'],
  '#ece6d8': ['text-primary', 'primary text, completed ring segments, light button fill (start / next scramble / play)'],
  '#3dbfad': ['teal', 'accent: nav underline, status dot, lit/active arc, good deltas, skip / pseudo-pair callouts'],
  '#16403a': ['teal-dim', 'dark teal fill: current-move pill, callout pills, selected speed chip'],
  '#0b1f1c': ['teal-ink', 'ink on teal: sparkle glyph inside a teal marker dot, "better line" label'],
  '#e6a642': ['amber', 'warning: wrong turn, detour, pause, +2, review current segment'],
  '#ec6b5f': ['coral', 'DNF text and the DNF hatch pattern stripes'],
  '#000': ['shadow', 'cube contact-shadow ellipse (at .35 opacity)'],
  '#2a2d33': ['sticker-unknown', 'neutral/unknown sticker in the OLL drill (A-08)'],
};

/** Sticker colour families keyed by the TOP-face hex. left/right shades are discovered from geometry. */
export const STICKER_FAMILIES = {
  '#f4f4f0': 'white',
  '#ffd43b': 'yellow',
  '#2563eb': 'blue',
  '#16a34a': 'green',
  '#e5302b': 'red',
  '#ff7a1a': 'orange',
};

/** key "family|size|weight|fill" -> role. Anchor and letter-spacing do not change the role. */
export const TYPE_ROLES = {
  'manrope|20|800|#ece6d8': 'wordmark',
  'manrope|17|800|#ece6d8': 'wordmark (phone)',
  'manrope|15|700|#ece6d8': 'nav item, active (also dark-button label)',
  'manrope|15|500|#9a9486': 'nav item, inactive (also one-line hints)',
  'manrope|120|300|#6d675c': 'timer, idle (0.00)',
  'manrope|128|300|#ece6d8': 'timer, running',
  'manrope|124|300|#ece6d8': 'timer, result',
  'manrope|168|300|#ece6d8': 'inspection countdown digit',
  'manrope|108|600|#3dbfad': 'big move glyph (move to turn now)',
  'manrope|84|600|#e6a642': 'big move glyph, wrong turn',
  'manrope|16|500|#9a9486': 'move description (under the big glyph)',
  'manrope|16|600|#e6a642': 'wrong-turn headline',
  'manrope|16|600|#ece6d8': 'review headline',
  'manrope|15|700|#141311': 'button label on light pill (next scramble, replay, open this solve)',
  'manrope|17|700|#141311': 'button label, large (start; phone next scramble / replay)',
  'manrope|15|700|#0b1f1c': 'button label on teal pill',
  'manrope|15|600|#9a9486': 'quiet action (more..., stop, back to results)',
  'manrope|15|600|#ece6d8': 'secondary action (review, replay, history)',
  'manrope|12.5|500|#9a9486': 'keycap action word (settings, command, stop ...)',
  'manrope|24|700|#3dbfad': 'stage title while solving',
  'manrope|19|500|#ece6d8': 'coach body copy (desktop)',
  'manrope|16|500|#ece6d8': 'coach body copy (phone)',
  'manrope|20|700|#ece6d8': 'inspection plan headline / history stat value',
  'manrope|20|700|#3dbfad': 'history stat value, teal (pb)',
  'manrope|56|300|#e6a642': 'review move counter ("move 4 of 8")',
  'manrope|14|500|#9a9486': 'instruction text (replay hints)',
  'manrope|14|500|#e6a642': 'marker "!" glyph',
  'manrope|14|600|#ece6d8': 'phone nav link (history / results)',
  'manrope|12|500|#9a9486': 'phone player meta',
  'manrope|13|500|#9a9486': 'past-solve caption',
  'manrope|13|600|#ece6d8': 'history filter chip',
  'manrope|17|700|#3dbfad': 'phone stage title',
  'manrope|17|700|#ece6d8': 'drill answer label',
  'manrope|22|600|#ece6d8': 'history row time',
  'manrope|22|600|#e6a642': 'history row time, +2',
  'manrope|22|600|#ec6b5f': 'history row time, DNF',
  'manrope|24|600|#ece6d8': 'drill stat value',
  'manrope|24|700|#ece6d8': 'drill question',
  'manrope|36|700|#ece6d8': 'page title',
  'manrope|40|300|#3dbfad': 'drill combo value',
  'manrope|76|300|#ece6d8': 'history headline time',
  'manrope|84|300|#ece6d8': 'phone timer, result / replay',
  'manrope|92|300|#ece6d8': 'phone timer, live',
  'manrope|96|300|#ece6d8': 'replay time',
  'mono|11.5|500|#d9d2c3': 'keycap label inside the primary pill (space / enter)',
  'mono|11|500|#d9d2c3': 'keycap label',
  'mono|11|400|#d9d2c3': 'drill choice number',
  'mono|11|400|#3dbfad': 'phone orbit split, good',
  'mono|11|400|#ece6d8': 'phone orbit split, neutral',
  'mono|11|400|#e6a642': 'phone orbit split, slow',
  'mono|11|400|#9a9486': 'phone config / replay total',
  'mono|11|500|#3dbfad': 'history PB badge',
  'mono|12|400|#6d675c': 'orbit stage label and sub-value, not yet reached (name, ~estimate)',
  'mono|12|400|#9a9486': 'config / status / stats line; reached stage name',
  'mono|12|400|#3dbfad': 'stage delta, faster than plan',
  'mono|12|400|#ece6d8': 'stage delta, on plan',
  'mono|12|400|#e6a642': 'stage delta, slower than plan / annotation',
  'mono|12|500|#3dbfad': 'callout text (pseudo pair, EO skip, live stage name)',
  'mono|12|500|#9a9486': 'replay speed chip, inactive',
  'mono|12|500|#e6a642': 'callout text, warning (detour, pause, coach)',
  'mono|13|400|#6d675c': 'move counter ("move 13 of 20")',
  'mono|13|400|#9a9486': 'drill progress',
  'mono|13|500|#ece6d8': 'inspection called time / drill title',
  'mono|13|500|#9a9486': 'inspection tick label',
  'mono|13|500|#e6a642': 'inspection +2 tick label',
  'mono|13|500|#ec6b5f': 'inspection DNF tick label',
  'mono|13|500|#3dbfad': 'review inner-ring move, better line',
  'mono|13|500|#6d675c': 'review inner-ring move, not on line',
  'mono|14|400|#6d675c': 'orbit move label, done (A-02)',
  'mono|14|400|#9a9486': 'solve delta line / replay total',
  'mono|15|500|#3dbfad': 'stage value, live / plan moves',
  'mono|15|500|#ece6d8': 'stage value (solving, replay)',
  'mono|16|400|#ece6d8': 'orbit move label, upcoming (A-02) / review outer done',
  'mono|16|400|#9a9486': 'review outer-ring move, later',
  'mono|16|500|#ece6d8': 'stage value (results)',
  'mono|17|500|#ece6d8': 'history solve number',
  'mono|20|500|#e6a642': 'review current move glyph',
  'mono|21|500|#3dbfad': 'orbit current-move pill text',
  'mono|21|500|#e6a642': 'orbit current-move pill text, wrong turn',
  'mono|28|500|#ece6d8': 'replay move glyph',
};

/** "stroke|width|opacity" -> role of a ring segment. */
export const SEGMENT_ROLES = {
  '#34312b|3|': 'idle (not reached)',
  '#6d675c|5|': 'done, quiet (scramble progress)',
  '#3dbfad|8|': 'active / lit',
  '#e6a642|8|': 'active, wrong turn',
  '#ece6d8|6|': 'done',
  '#3dbfad|6|': 'done, better than plan',
  '#e6a642|6|': 'done, worse than plan',
  '#9a9486|6|': 'review: later segment',
  '#e6a642|9|': 'review: current segment',
  '#3dbfad|3|0.9': 'skip bridge',
  '#4d3715|7|': 'inspection +2 window',
  'url(#hatch)|7|': 'inspection DNF window (hatched)',
  '#2a2823|3|': 'inspection template (inner ring)',
  '#6d675c|5|0': 'review inner: not on better line',
  '#3dbfad|5|': 'review inner: better line',
  '#ec6b5f|6|1': 'history mini-ring, DNF',
  '#3dbfad|6|1': 'history mini-ring, selected',
};

/** First-line prose per frame: what the screen is. Numbers are generated elsewhere. */
export const FRAME_TITLES = {
  'A-01-idle': 'Solve, idle: solved cube, ghost orbit (stage plan), 0.00 timer, start pill',
  'A-02-scramble': 'Scramble guidance: moves orbit shows done / current / upcoming, header dimmed to .3',
  'A-02b-wrong-turn': 'Scramble guidance, wrong turn: current segment and pill turn amber',
  'A-03-inspection': 'Inspection: countdown ring, plan text left, +2 / DNF windows',
  'A-04-solving': 'Solving: live stage ring, live splits and timer',
  'A-05-results': 'Results: per-stage splits, markers, coach text, next-scramble pill',
  'A-06-review': 'Review a moment: outer (yours) vs inner (better line) rings',
  'A-07-history': 'History: solve list with mini rings, selected-solve orbit on the right',
  'A-08-drill': 'Drill: OLL recognition round on the orbit',
  'A-09-phone': 'Phone sheet: live solve (left device) and result (right device)',
  'A-10-past-solve': 'Past solve: results layout opened from history',
  'A-11-replay': 'Replay: scrub the ring, transport controls, speed chips',
  'A-12-phone-past': 'Phone sheet: past solve replay (left) and past result (right)',
};

/**
 * Names for the A-01 anchors, matched by text content / tag. Order matters
 * only for duplicates (the n-th occurrence gets the n-th name).
 */
export const ANCHOR_NAMES = {
  'text:cubesight': 'header.wordmark',
  'text:solve': 'header.nav.solve',
  'text:drills': 'header.nav.drills',
  'text:algs': 'header.nav.algs',
  'text:progress': 'header.nav.progress',
  'text:history': 'header.nav.history',
  'text:GAN 356 i3': 'header.cubeName',
  'text:84%': 'header.battery',
  'text:0.00': 'timer',
  'text:start': 'startPill.label',
  'text:space': 'startPill.keycapLabel',
  'text:cfop · 2-look · pseudo pairs · wca inspection': 'config.line',
  'text:tab': 'keys.settings.keycapLabel',
  'text:settings': 'keys.settings.action',
  'text:esc': 'keys.command.keycapLabel',
  'text:command': 'keys.command.action',
  'text:ao5 14.62 · ao12 15.03 · pb 12.41': 'stats.line1',
  'text:23 solves today · history': 'stats.line2',
};
